### ISSUE TITLE
Terraform Plugin SDK v2 Upgrade

### ISSUE THREAD

**Issue by danijeel** [appgate/sdp-terraform-provider#71]
https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html

helpful tools:
https://github.com/hashicorp/tf-sdk-migrator#tf-sdk-migrator-v2upgrade-migrate-from-sdkv1-to-sdkv2

**Comment by dirtyonekanobi** [comment]
Hey @danijeel , quick question.

I've got the v2 upgrade working here - https://github.com/dirtyonekanobi/sdp-terraform-provider/tree/djj-tfv2-sdk

I'm in the process of rewriting the resource tests to confirm to the new `TypeSet` changes in the SDK. 

Are the current tests passing w/100% coverage?

**Comment by danijeel** [comment]
yes, all acceptance tests and unit tests are passing in master right now. Its fairly high test coverage with the acceptance test, but it does not cover all edge cases. We haven't generated any number test coverage.

**Comment by danijeel** [comment]
Fixed in #73
