### ISSUE TITLE
Appliance Features can't be disabled once enabled

### ISSUE THREAD

**Issue by infosec-shinobi** [appgate/sdp-terraform-provider#75]
ssh_server, prometheus_exporter, and healthcheck_server code blocks can't be disabled once enabled.

Problem lines:

- https://github.com/appgate/sdp-terraform-provider/blob/d9c23837c9a4ad7060573ad426aaf7e7ef9dcf6a/appgate/resource_appgate_appliance.go#L1432
- https://github.com/appgate/sdp-terraform-provider/blob/d9c23837c9a4ad7060573ad426aaf7e7ef9dcf6a/appgate/resource_appgate_appliance.go#L1459
- https://github.com/appgate/sdp-terraform-provider/blob/d9c23837c9a4ad7060573ad426aaf7e7ef9dcf6a/appgate/resource_appgate_appliance.go#L1471

"Enabled" field is being hardcoded to "true" instead of a call to the "GetEnabled" function. 

PR to address coming shortly.

**Comment by danijeel** [comment]
Fixed in #76
